### ISSUE TITLE
run default unit test case have some error 

### ISSUE THREAD

**Issue by Old-Rascal** [eulery/opentsdb-java-sdk#3]
HttpException(errorResponse=调用OpenTSDB http api发生错误，响应码:400,错误信息:One or more data points had errors

**Comment by eulery** [comment]
这个错误是在批量写入时，有个别(也可能多个或者所有)point写入失败，是在opentsdb中发生的错误
opentsdb源码如下：
`

    if (!show_summary && !show_details) {
          if (failures + failed_writes > 0) {
            query.sendReply(HttpResponseStatus.BAD_REQUEST, 
                query.serializer().formatErrorV1(
                    new BadRequestException(HttpResponseStatus.BAD_REQUEST,
                "One or more data points had errors", 
                "Please see the TSD logs or append \"details\" to the put request")));
          } else {
            query.sendReply(HttpResponseStatus.NO_CONTENT, "".getBytes());
          }
        }
`
可以看到当写入时没有设置show_summary或者show_details，并且有错误数量时，就会返回你这个异常

你可以在创建opentsdbClient的时候加上写入回调batchPutCallBack，DetailResult会包含错误的信息
另外写入失败你可以看看是不是没有开启opentsdb的自动创建metric，我之前也遇到过这个问题

**Comment by Old-Rascal** [comment]
我在写入单条的时候也是会报这个错误。
tags 的数量我已经改了源码取测试，但是还是一样的。我再去改改看。

**Comment by eulery** [comment]
> 我在写入单条的时候也是会报这个错误。
> tags 的数量我已经改了源码取测试，但是还是一样的。我再去改改看。

我建议可以先使用opentsdb的http api手动调试一下，这个sdk只是封装了opentsdb的http api，你这个错误和sdk无关，直接使用http api，应该能获取到更多错误的信息

**Comment by Old-Rascal** [comment]
谢谢。
